import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PageTemplate } from "@/components"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>On Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <PageTemplate>

    </PageTemplate>

    </div>
  )
}

export default Home
