import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PageTemplate, Dishe } from "@/components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Front On Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <PageTemplate>

      <Dishe />
    </PageTemplate>

    </div>
  );
};

export default Home;
